sudo: required

language: php

php:
  - '7.0'

services:
  - docker

before_install:
  - docker info

script:
  - docker run -d --name wiremock -p 8080:8080 rodolpheche/wiremock
  - docker logs wiremock
  - docker exec wiremock curl -sS http://localhost:8080/__admin/
  - docker rm -f wiremock

install:
    - composer install --prefer-dist

script: make test
